### ISSUE TITLE
Fallender Ball mit P5.js

### ISSUE THREAD

**Issue by jpgerdeman** [0010011012/SP_vfst_2023#5]
Lege dir folgende zwei Dateien lokal an

Eine Datei `ball.html` mit folgendem Inhalt
```
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.11/p5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.11/addons/p5.dom.min.js"></script>
  </head>
  <body>
    <script src="ball.js"></script>
  </body>
</html>
```

Eine Datei `ball.js` mit folgendem Inhalt
```
function setup(){
  
  //Initialisation of canvas, objects, variables etc.
 
}

function draw(){
  
  //The drawing loop - updates at a constant rate declared in setup
 
}
```

Das ist unser Grundrahmen für die Arbeit mit [P5](https://p5js.org/). P5 ist eine grafische Bibliothek, um Anfängern und Künstlern den Einstieg zu erleichtern interaktive grafische Elemente zu entwerfen.

Wenn Du die Seite im Browser aufrufst, passiert folgendes.
- Die Datei wird eingelesen, alle Funktionen, und Variablen die Du außerhlab setup und draw definierst stehen dir zur Verfügung
- Die setup Methode wird einmalig aufgerufen
- Die draw Methode wird immer wieder in einer Schleife aufgerufen. 

Schreibe folgendes in die setup Methode, um eine Zeichenfläche vorzubereiten
```
createCanvas(720, 400);
```

In der draw Methode fügst Du folgendes ein
```
// x koord, y koord, radius
ellipse(56, 46, 55);
```

Nun ändere den Code so, dass die y-Koordinate bei jedem Aufruf von draw um eins erhöht wird.

- Was passiert?
- Wo sind die Unterscheide zum kartesischen Koordinatensystem aus der Schule?

**Comment by 0010011012** [comment]
```
point_y=350;
point_x=350;
velocity_x=5;
velocity_y=6;
screen_x=700;
screen_y=700;
function setup(){
	createCanvas(screen_x, screen_y);
  
  //Initialisation of canvas, objects, variables etc.
}
function draw(){
	createCanvas(screen_x, screen_y);
	// x koord, y koord, radius
	ellipse(point_x , point_y , 55);
	point_y+=velocity_y;
	point_x+=velocity_x;

	//The drawing loop - updates at a constant rate declared in setup


	if(point_y>screen_y || point_y<0){
		velocity_y=-velocity_y;
	}

	if(point_x>screen_x || point_x<0){
		velocity_x=-velocity_x;
	}
}
```
